language: node_js
node_js:
  - "8"

cache:
  directories:
    - node_modules

before_install:
#- sudo apt-get install google-chrome-stable

install:
    - npm install

script:
    - npm run build
    - npm run build-copy
    - rm -rf ./src ./test ./coverage ./script ./.babelrc
after_success:
#- cat ./coverage/lcov.info | node_modules/.bin/coveralls --verbose
#- rm -rf ./coverage

branches:
  only:
    - master
    - production

before_deploy:
  #- npm run build
  - npm run build-copy
  - rm -rf ./src ./test ./coverage ./script ./.babelrc

deploy:
  provider: npm
  email: "$GH_EMAIL"
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    branch: production

after_script:
  #- cd utils
  - git init
  - git config user.name "${GH_NAME}"
  - git config user.email "${GH_EMAIL}"
  - git add .
  - git commit -m "update utils"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:release

env:
  global:
   - GH_REF: github.com/hjaiim/utils.git

notifications:
  email:
    recipients:
      - hjaiim@163.com
    on_success: change
    on_failure: always
