language: node_js
node_js:
  - "8"

cache:
  directories:
    - node_modules

install:
    - npm install

script:
    - npm run build

branches:
  only:
    - master

deploy:
  provider: npm
  email: "$GH_EMAIL"
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    branch: production
    #branch: master

after_script:
  - cd ./dist
  - git init
  - git config user.name "${GH_NAME}"
  - git config user.email "${GH_EMAIL}"
  - git add .
  - git commit -m "update utils"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages

env:
  global:
   - GH_REF: github.com/hjaiim/utils.git

notifications:
  email:
    recipients:
      - hjaiim@163.com
    on_success: change
    on_failure: always
