language: node_js
node_js:
  - "8"

notifications:
  email:
    recipients:
      - hjaiim@163.com
  on_success: change
  on_failure: always

before_install:
  - sudo apt-get install google-chrome-stable
install:
    - npm install
script:
    - npm run test